## Create Matrix using 2-D array and it's Mathematical operations

https://www.kdnuggets.com/2018/05/wtf-tensor.html

In [ ]:
import numpy as np

#### Creating a two-dimensional matrix

In [ ]:
a = np.array([1, 2, 3, 11, 22, 33, 6, 9, 12]).reshape(3, 3)

a

array([[ 1,  2,  3],
       [11, 22, 33],
       [ 6,  9, 12]])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.ndim

2

In [ ]:
type(a)

numpy.ndarray

In [ ]:
b = np.array([i for i in range(0, 18, 2)]).reshape(3, 3)

b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
c = np.array([i for i in range(6)]).reshape(3, 2)

c

array([[0, 1],
       [2, 3],
       [4, 5]])

### Adding two matrices

In [ ]:
def add_matrices(A, B):
    
    add = []
    
    for i in range(len(A)):
        add.append(A[i] + B[i])
        
    return np.array(add)

In [ ]:
a.shape

(3, 3)

In [ ]:
b.shape

(3, 3)

In [ ]:
print('First matrix: \n', a)
print('\nSecond matrix: \n', b)
print('\nSum: \n', add_matrices(a, b))

First matrix: 
 [[ 1  2  3]
 [11 22 33]
 [ 6  9 12]]

Second matrix: 
 [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]

Sum: 
 [[ 1  4  7]
 [17 30 43]
 [18 23 28]]


In [ ]:
a + b

array([[ 1,  4,  7],
       [17, 30, 43],
       [18, 23, 28]])

#### For addition shape should be same of both matrix

In [ ]:
a.shape

(3, 3)

In [ ]:
c.shape

(3, 2)

##### This will throw an error

In [ ]:
a + c

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

### Subtracting two matrix

In [ ]:
def subtract_matrices(A, B):
    
    add = []
    
    for i in range(len(A)):
        add.append(A[i] - B[i])
        
    return np.array(add)

In [ ]:
print('First matrix: \n', a)
print('\nSecond matrix: \n', b)
print('\nDifference: \n', subtract_matrices(a, b))

First matrix: 
 [[ 1  2  3]
 [11 22 33]
 [ 6  9 12]]

Second matrix: 
 [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]

Difference: 
 [[ 1  0 -1]
 [ 5 14 23]
 [-6 -5 -4]]


In [ ]:
a - b

array([[ 1,  0, -1],
       [ 5, 14, 23],
       [-6, -5, -4]])

#### Matrix multiplication

In [ ]:
print('First matrix: \n', a)
print('\nSecond matrix: \n', b)
print('\nDot: \n', np.dot(a,b))

First matrix: 
 [[ 1  2  3]
 [11 22 33]
 [ 6  9 12]]

Second matrix: 
 [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]

Dot: 
 [[ 48  60  72]
 [528 660 792]
 [198 252 306]]


In [ ]:
np.matmul(a,b)

array([[ 48,  60,  72],
       [528, 660, 792],
       [198, 252, 306]])

#### Determinant

In [ ]:
a

array([[ 1,  2,  3],
       [11, 22, 33],
       [ 6,  9, 12]])

In [ ]:
det_a = np.linalg.det(a)

det_a

-9.15933995315751e-16

In [ ]:
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
det_b = np.linalg.det(b)

det_b

0.0

#### Transpose of matrix

If the rows and columns in a matrix are interchanged, the new matrix is called the transpose of the original matrix

In [ ]:
a

array([[ 1,  2,  3],
       [11, 22, 33],
       [ 6,  9, 12]])

In [ ]:
a.T

array([[ 1, 11,  6],
       [ 2, 22,  9],
       [ 3, 33, 12]])

In [ ]:
np.transpose(a)

array([[ 1, 11,  6],
       [ 2, 22,  9],
       [ 3, 33, 12]])

#### Trace of matrix

Trace is the sum of the elements on the main diagonal

In [ ]:
a

array([[ 1,  2,  3],
       [11, 22, 33],
       [ 6,  9, 12]])

In [ ]:
np.trace(a)

35

### Types of Matrices

https://www.math24.net/properties-matrices

### Square Matrix

where number of rows and columns are same

In [ ]:
a

array([[ 1,  2,  3],
       [11, 22, 33],
       [ 6,  9, 12]])

In [ ]:
a.shape

(3, 3)

#### `a` is a square matrix because here number of rows and columns are same

### Symmetric Matrix

A square matrix is called a symmetric matrix if the elements of the matrix are symmetric with respect to the main diagonal

In [ ]:
a

array([[ 1,  2,  3],
       [11, 22, 33],
       [ 6,  9, 12]])

In [ ]:
symmetric_mat = a.dot(a.T)

symmetric_mat

array([[  14,  154,   60],
       [ 154, 1694,  660],
       [  60,  660,  261]])

In [ ]:
symmetric_mat[1][2]

660

In [ ]:
symmetric_mat[2][1]

660

#### Same as above 

In [ ]:
symmetric_mat[0][2] == symmetric_mat[2][0]

True

In [ ]:
symmetric_mat[0][1] == symmetric_mat[1][0]

True

#### So this is a symmetric matrix

### Diagonal Matrix
A square matrix is called diagonal if all its elements outside the main diagonal are equal to zero

In [ ]:
diagonal_mat = np.zeros((3, 3), dtype='int32')

np.fill_diagonal(diagonal_mat, 2)

diagonal_mat

array([[2, 0, 0],
       [0, 2, 0],
       [0, 0, 2]], dtype=int32)

### Identity Matrix

A diagonal matrix is called the identity matrix if the elements on its main diagonal are all equal to 
1.(All other elements are zero)

In [ ]:
identity_mat = np.zeros((3, 3), dtype='float')

np.fill_diagonal(identity_mat, 1)

identity_mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Zero Matrix or Null Matrix

In [ ]:
zero_mat = np.zeros((3, 3))

zero_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Invertible Matrix

if AB = BA = I, then it's called Invertival Matrix


- Thus B is the inverse of A, in other

AB = BA = I

B = $A^-$$^1$

or 

A = $B^-$$^1$

##### Lets take a new matrix

In [ ]:
a = np.array([[2, 3],
              [2, 2]])

a

array([[2, 3],
       [2, 2]])

In [ ]:
b = np.array([[-1, 1.5],
              [1, -1]])

b

array([[-1. ,  1.5],
       [ 1. , -1. ]])

In [ ]:
a.dot(b)

array([[1., 0.],
       [0., 1.]])

##### which is a identity matrix, now we will inverse the matrix a and it should be equal to b

In [ ]:
inverse_a = np.linalg.inv(a)

inverse_a

array([[-1. ,  1.5],
       [ 1. , -1. ]])

In [ ]:
inverse_a == b

array([[ True,  True],
       [ True,  True]])

### Elementwise Product OR Hadamard Product

https://numpy.org/doc/stable/reference/generated/numpy.multiply.html

https://stackoverflow.com/questions/40034993/how-to-get-element-wise-matrix-multiplication-hadamard-product-in-numpy

In [ ]:
a

array([[2, 3],
       [2, 2]])

In [ ]:
b

array([[-1. ,  1.5],
       [ 1. , -1. ]])

In [ ]:
a * b

array([[-2. ,  4.5],
       [ 2. , -2. ]])

In [ ]:
np.multiply(a, b)

array([[-2. ,  4.5],
       [ 2. , -2. ]])

### Dot product or Scalar product or Matrix product

https://en.wikipedia.org/wiki/Dot_product#Algebraic_definition

https://numpy.org/devdocs/user/quickstart.html#array-creation

Note:- For Multiplication of two matrix or vector it must follow
- Column of first matrix(a) must be equal to row of second matrix(b)

In [ ]:
a

array([[2, 3],
       [2, 2]])

In [ ]:
b

array([[-1. ,  1.5],
       [ 1. , -1. ]])

In [ ]:
a.shape, b.shape

((2, 2), (2, 2))

##### here, col(a) = row(b)

In [ ]:
a.dot(b)

array([[1., 0.],
       [0., 1.]])

In [ ]:
a @ b

array([[1., 0.],
       [0., 1.]])

#### Let's take another matrix

In [ ]:
p = np.array(np.random.randint(-5, 5, size=(3, 2)))

p

array([[ 4, -1],
       [-3,  4],
       [-1, -3]])

In [ ]:
q = np.array(np.random.randint(5, 10, size=(3, 2)))

q

array([[7, 7],
       [6, 6],
       [8, 5]])

In [ ]:
p.shape, q.shape

((3, 2), (3, 2))

##### Here col(p) is not equal to row(q) so dot product will throw error

In [ ]:
p.dot(q)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

### Calculate Rank of matrix

https://stattrek.com/matrix-algebra/matrix-rank.aspx

In [ ]:
from numpy.linalg import matrix_rank

In [ ]:
p

array([[ 4, -1],
       [-3,  4],
       [-1, -3]])

In [ ]:
matrix_rank(p)

2

In [ ]:
a

array([[2, 3],
       [2, 2]])

In [ ]:
matrix_rank(a)

2

## Using special matrix operations in SciPy
Note:- SciPy contains all functions present in NumPy plus a few more

In [ ]:
from scipy.sparse import identity, diags

### Indentity matrix using SciPy

In [ ]:
identity(2)

<2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements (1 diagonals) in DIAgonal format>

In [ ]:
idty_mat = identity(2).toarray()

idty_mat

array([[1., 0.],
       [0., 1.]])

In [ ]:
idty_mat = identity(3).toarray()

idty_mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Scalar matrix

https://stattrek.com/statistics/dictionary.aspx?definition=scalar-matrix

In [ ]:
scalar_mat  = diags([2, 2, 2], 0).toarray()

scalar_mat

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [ ]:
diag_mat  = diags([2, 1, 3], 0).toarray()

diag_mat

array([[2., 0., 0.],
       [0., 1., 0.],
       [0., 0., 3.]])