In [ ]:
import numpy as np

## Matrix Properties

In [ ]:
a = np.array(np.random.randint(-5, 5, size=(3, 3)))

b = np.array(np.random.randint(-10, -5, size=(3, 3)))

c =  np.array(np.random.randint(5, 10, size=(3, 3)))

In [ ]:
a

array([[ 2, -1,  3],
       [ 1,  4,  1],
       [-5, -4, -5]])

In [ ]:
b

array([[ -6,  -6,  -8],
       [ -6,  -6, -10],
       [-10,  -7,  -6]])

In [ ]:
c

array([[5, 9, 6],
       [9, 7, 8],
       [6, 5, 5]])

### Commutative

a+b = b+a

In [ ]:
a + b

array([[ -4,  -7,  -5],
       [ -5,  -2,  -9],
       [-15, -11, -11]])

In [ ]:
b + a

array([[ -4,  -7,  -5],
       [ -5,  -2,  -9],
       [-15, -11, -11]])

In [ ]:
a + b == b + a

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### Associative

a + (b + c) = (a + b) + c

In [ ]:
a + (b+c)

array([[ 1,  2,  1],
       [ 4,  5, -1],
       [-9, -6, -6]])

In [ ]:
(a+b) + c

array([[ 1,  2,  1],
       [ 4,  5, -1],
       [-9, -6, -6]])

In [ ]:
a + (b+c) == (a+b) + c

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### Addictive Identity

A+O = A

In [ ]:
a

array([[ 2, -1,  3],
       [ 1,  4,  1],
       [-5, -4, -5]])

In [ ]:
zero_mat = np.zeros((3, 3))

zero_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a + zero_mat

array([[ 2., -1.,  3.],
       [ 1.,  4.,  1.],
       [-5., -4., -5.]])

In [ ]:
a + zero_mat == a

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### Properties of the Transpose of a Matrix

- ($a^t)^t$ = a
- $(a + b)^t$ = $a^t$ + $b^t$
- $(ab)^t$ = $b^ta^t$
- $(ra)^t$ = $ra^t$


##### ($a^t)^t$ = a

In [ ]:
a

array([[ 2, -1,  3],
       [ 1,  4,  1],
       [-5, -4, -5]])

In [ ]:
(a.T).T

array([[ 2, -1,  3],
       [ 1,  4,  1],
       [-5, -4, -5]])

In [ ]:
(a.T).T == a

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#####  $(a + b)^t$ = $a^t$ + $b^t$

In [ ]:
(a + b).T

array([[ -4,  -5, -15],
       [ -7,  -2, -11],
       [ -5,  -9, -11]])

In [ ]:
a.T + b.T

array([[ -4,  -5, -15],
       [ -7,  -2, -11],
       [ -5,  -9, -11]])

In [ ]:
(a + b).T == a.T + b.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

##### - $(ab)^t$ = $b^ta^t$

In [ ]:
(a.dot(b)).T

array([[-36, -40, 104],
       [-27, -37,  89],
       [-24, -54, 110]])

In [ ]:
(b.T).dot(a.T)

array([[-36, -40, 104],
       [-27, -37,  89],
       [-24, -54, 110]])

In [ ]:
(a.dot(b)).T == (b.T).dot(a.T)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

##### $(ra)^t$ = $ra^t$

In [ ]:
r = 5

r

5

In [ ]:
r*a

array([[ 10,  -5,  15],
       [  5,  20,   5],
       [-25, -20, -25]])

In [ ]:
(r*a).T

array([[ 10,   5, -25],
       [ -5,  20, -20],
       [ 15,   5, -25]])

In [ ]:
r * a.T

array([[ 10,   5, -25],
       [ -5,  20, -20],
       [ 15,   5, -25]])

In [ ]:
(r*a).T == r * a.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])